export const ADD_NEWSTAFF = 'ADD_NEWSTAFF';

export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_LOADING = 'STAFF_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';

export const ADD_STAFFS_SALARY = 'ADD_STAFFS_SALARY';
export const SALARY_LOADING = 'SALARY_LOADING';
export const SALARY_FAILED = 'SALARY_FAILED';

export const DELETE_STAFF = 'DELETE_STAFF';